0f
0f 12ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿17
0f 12³ 1a>>>1e                      matrixxx UEFI BOOT                            1a<<<12 ³17
0f 12ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ17
0f 12                                                                              17
0f 12                                                                              17
0f 12                                                                              17
0f 12 HINWEIS: Im UEFI-Modus kann es passieren, dass der Bildschirm bis zum Start  17
0f 12 des Grafik-Modus dunkel bleibt, und die Bootmeldungen unsichtbar sind.       17
0f 12                                                                              17
0f 12                                                                              17
0f 12                                                                              17
0f 12                                                                              17
0f 12                                                                              17
0f 12                                                                              17
0f 12                                                                              17
0f 12                                                                              17
0f
                                                            RELEASE 2024-01-01

